In [8]:
def van_mat():
    list = input("enter list of numbers:").split(",")
    import numpy as np
    x = np.fromiter(list,int)
    N = int(input("please enter a number"))
    print(np.column_stack([x**(N-1-i) for i in range(N)]))

In [9]:
van_mat()

enter list of numbers:1,2,3,4,5
please enter a number5
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
